# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: fr
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        max_history: 1
  - name: KerasPolicy
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        max_history: 1
  - name: MappingPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.6
    core_threshold: 0.5
    fallback_action_name: 'utter_phrase_hors_sujet_0'
